### ISSUE TITLE
Dane w raporcie z walidacji

### ISSUE THREAD

**Issue by Mateusz456789** [MarcinLebiecki/WalidatorPlikowGML#1]
W generowanym raporcie z walidacji pliku GML pomocnym w lokalizowaniu błędów byłaby kolumna z wartością id obiektu .

**Comment by MarcinLebiecki** [comment]
Na etapie walidacji nie przewidujemy obecnie dodawania id obiektów. Przy kontroli atrybutów i relacji będzie odniesienie do identyfikatorów obiektów.

**Comment by MarcinLebiecki** [comment]
Na ten moment zamykam wątek.
