### ISSUE TITLE
Zbyt długie pola tekstowe

### ISSUE THREAD

**Issue by andstaw** [MarcinLebiecki/WalidatorPlikowGML#2]
W przypadku plików zawierających „długie” pola tekstowe (np. opis zmiany w pliku GML z całej bazy EGiB) walidator się zatrzymuje. Raport wskazuje błąd „ogromny węzeł tekstowy”.

**Comment by MarcinLebiecki** [comment]
Na ten moment brak rozwiązania tego problemu. Zagadnienie pozostaje otwarte.
