### ISSUE TITLE
Nazwa pliku z raportem

### ISSUE THREAD

**Issue by andstaw** [MarcinLebiecki/WalidatorPlikowGML#3]
Fajnie by było, jakby wynikowy plik z raportem zawierał również datę i godzinę końca walidacji np. w formacie YYYY-MM-DD_hh.mm

**Comment by MarcinLebiecki** [comment]
Dziękuję za uwagę. Dodałem datę i godzinę do nazwy pliku. Zmiana pojawi się niedługo w wersji 1.0.1.

**Comment by MarcinLebiecki** [comment]
Zamykam wątek.
