### ISSUE TITLE
Zamknięcie pliku logu

### ISSUE THREAD

**Issue by BernardBielecki** [MarcinLebiecki/WalidatorPlikowGML#4]
https://github.com/MarcinLebiecki/WalidatorPlikowGML/blob/1eb491c84322d24622da63a757100972624897b3/walidatorPlikowGML.py#L293

Proponuję zamknięcie pliku logu niezależnie od wyniku walidacji.

**Comment by MarcinLebiecki** [comment]
Dziękuję za uwagę. Poprawiłem błąd i w wersji 1.0.1 będzie już zamykanie niezależnie od wyniku walidacji.

**Comment by MarcinLebiecki** [comment]
Zamykam wątek.
