### ISSUE TITLE
Wielkość liter w rozszerzeniu gml/GML

### ISSUE THREAD

**Issue by andstaw** [MarcinLebiecki/WalidatorPlikowGML#6]
Dzień dobry,
Ostatnio ktoś mi zwrócił uwagę na to, co w ogóle nie przyszłoby mi do głowy.
Do naszego PODGiK jeden z wykonawców oddaje wraz z operatem pliki GML z bazy EGiB. Walidator zwraca kilka błędów, w których podejrzewa błędna przestrzeń nazw, ale (i tu najciekawsze) po zmianie rozszerzenia .gml na .GML to wtedy walidacja kończy się pozytywnie.
Czy mógłby się Pan temu przyjrzeć?

**Comment by MarcinLebiecki** [comment]
Błąd został poprawiony.
