### ISSUE TITLE
EGB_RodzajDokumentuType

### ISSUE THREAD

**Issue by klegutko** [MarcinLebiecki/WalidatorPlikowGML#7]
Dla EGB_RodzajDokumentuType w schemacie EGIB_1.8.xsd
wartości enumeracji 23 powtarzają się:		
```
<enumeration value="23">
	<annotation>
		<appinfo>
			<gml:description>zawiadomienieZPESEL</gml:description>
		</appinfo>
	</annotation>
</enumeration>
<enumeration value="23">
	<annotation>
		<appinfo>
			<gml:description>zgloszenieZmianySposobuUzytkowania</gml:description>
		</appinfo>
	</annotation>
</enumeration>
```

Używanie wartości 24 powoduję błędny wynik walidacji, kiedy w 
Rozporządzeniu Ministra Rozwoju, Pracy i Technologii z dnia 27 lipca 2021 r. w sprawie ewidencji gruntów i budynków
wartości to: 
«Enumeration»
EGB_RodzajDokumentu
 (...)
 zawiadomienieZPESEL = 23
 zgloszenieZmianySposobuUzytkowania = 24
 
Przykład:
Element '{ewidencjaGruntowIBudynkow:1.0}rodzajDokumentu': [facet 'enumeration'] Wartość '24' nie znajduje się na liście {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '19', '20', '21', '22', '23', '23'}.

**Comment by MarcinLebiecki** [comment]
W nowej wersji Walidatora plików GML v1.0.9 zostanie wykorzystany nowy schemat aplikacyjny do danych EGiB z poprawionym błędem wskazanym przez Pana.
